# Generated by Django 3.2 on 2021-04-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Del', 'Deluxe Suite'), ('Lux', 'Luxury Suite'), ('Pre', 'Premier Suite')], max_length=3),
        ),
    ]
