# Generated by Django 3.2 on 2021-04-20 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('proof', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=10)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Booking',
            new_name='BookingList',
        ),
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Deluxe Suite', 'Deluxe Suite'), ('Premier Suite', 'Premier Suite'), ('Luxury Suite', 'Luxury Suite')], max_length=15),
        ),
    ]
