# Generated by Django 3.2 on 2021-04-20 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20210420_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guests',
            new_name='Guest',
        ),
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Deluxe Suite', 'Deluxe Suite'), ('Luxury Suite', 'Luxury Suite'), ('Premier Suite', 'Premier Suite')], max_length=15),
        ),
    ]
