# Generated by Django 3.2 on 2021-04-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210420_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='address',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='city',
            field=models.CharField(default='pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(default='pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(default='pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='state',
            field=models.CharField(default='pending', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Luxury Suite', 'Luxury Suite'), ('Deluxe Suite', 'Deluxe Suite'), ('Premier Suite', 'Premier Suite')], max_length=15),
        ),
    ]
