# Generated by Django 3.2 on 2021-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210420_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='guest',
            name='user',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Premier Suite', 'Premier Suite'), ('Deluxe Suite', 'Deluxe Suite'), ('Luxury Suite', 'Luxury Suite')], max_length=15),
        ),
    ]
