# Generated by Django 3.2 on 2021-05-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210501_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Deluxe Suite', 'Deluxe Suite'), ('Premier Suite', 'Premier Suite'), ('Luxury Suite', 'Luxury Suite')], max_length=15),
        ),
    ]
