# Generated by Django 3.2 on 2021-05-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210501_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Luxury Suite', 'Luxury Suite'), ('Deluxe Suite', 'Deluxe Suite'), ('Premier Suite', 'Premier Suite')], max_length=15),
        ),
    ]
