# Generated by Django 3.2 on 2021-05-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rename_name_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='guestname',
        ),
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Luxury Suite', 'Luxury Suite'), ('Premier Suite', 'Premier Suite'), ('Deluxe Suite', 'Deluxe Suite')], max_length=15),
        ),
    ]
