# Generated by Django 3.2 on 2021-05-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210501_1044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_us',
        ),
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Deluxe Suite', 'Deluxe Suite'), ('Premier Suite', 'Premier Suite'), ('Luxury Suite', 'Luxury Suite')], max_length=15),
        ),
    ]
