# Generated by Django 3.2 on 2021-05-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20210516_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Deluxe Suite', 'Deluxe Suite'), ('Luxury Suite', 'Luxury Suite'), ('Premier Suite', 'Premier Suite')], max_length=15),
        ),
    ]
