# Generated by Django 3.2 on 2021-05-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Premier Suite', 'Premier Suite'), ('Deluxe Suite', 'Deluxe Suite'), ('Luxury Suite', 'Luxury Suite')], max_length=15),
        ),
    ]
