# Generated by Django 3.2 on 2021-05-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20210516_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Category',
            field=models.CharField(choices=[('Premier Suite', 'Premier Suite'), ('Luxury Suite', 'Luxury Suite'), ('Deluxe Suite', 'Deluxe Suite')], max_length=15),
        ),
    ]
